# The GitHub Actions docs (https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on)
# describe other options for 'on', 'pull_request' is a good default.
on:
  pull_request:
    types: [closed]

jobs:
  csv_update:
    name: UpdateCSV
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:

      # Checkout the base branch of the pull request (e.g. main/master).
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: infracost-json
          
      - name: Test artifact
        run: ls -R
        
      - name: Cat Variable
        id: cat-vars
        run: |
            echo "INFRACOST_STEP_DATE=$(cat infracost.json | jq -r '.metadata.vcsCommitTimestamp')" >> $GITHUB_OUTPUT
            echo "INFRACOST_STEP_SHA=$(cat infracost.json | jq -r '.metadata.vcsCommitSha')" >> $GITHUB_OUTPUT
            echo "COST=$(cat infracost.json | jq -r '.diffTotalMonthlyCost')" >> $GITHUB_OUTPUT

      - name: Append a line into a CSV
        uses: gr2m/write-csv-file-action@v1.x
        with:
          path: data/list.csv
          columns: commit-date,commit-sha,cost
          "commit-date": ${{ steps.cat-vars.outputs.INFRACOST_STEP_DATE }}
          "commit-sha": ${{ steps.cat-vars.outputs.INFRACOST_STEP_SHA }}
          "cost": ${{ steps.cat-vars.outputs.COST }}
  
      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{github.token}}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: CSV update
          file_pattern: 'data/*.csv'
          ref: ${{ github.head_ref }}