
on: [pull_request]

jobs:
  infracost:
    name: Infracost
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    env:
      TF_ROOT: .

    steps:

      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        # See https://github.com/infracost/actions/tree/master/setup for other inputs
        # If you can't use this action, see Docker images in https://infracost.io/cicd
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      # Checkout the base branch of the pull request (e.g. main/master).
      - name: Checkout base branch
        uses: actions/checkout@v3
        with:
          ref: '${{ github.event.pull_request.base.ref }}'

      # Generate Infracost JSON file as the baseline.
      - name: Generate Infracost cost estimate baseline
        run: |
          infracost breakdown --path=${TF_ROOT} \
                              --format=json \
                              --out-file=/tmp/infracost-base.json

      # Checkout the current PR branch so we can create a diff.
      - name: Checkout PR branch
        uses: actions/checkout@v3

      # Generate an Infracost diff and save it to a JSON file.
      - name: Generate Infracost diff
        run: |
          infracost diff --path=${TF_ROOT} \
                          --format=json \
                          --compare-to=/tmp/infracost-base.json \
                          --out-file=/tmp/infracost.json


      - name: Post Infracost comment
        id: post-comment-step
        run: |
            infracost comment github --path=/tmp/infracost.json \
                                     --repo=$GITHUB_REPOSITORY \
                                     --github-token=${{github.token}} \
                                     --pull-request=${{github.event.pull_request.number}} \
                                     --behavior=update
            echo "INFRACOST_STEP_DATE=$(cat infracost.json | jq -r '.metadata.vcsCommitTimestamp')" >> $GITHUB_OUTPUT
            echo "INFRACOST_STEP_SHA=$(cat infracost.json | jq -r '.metadata.vcsCommitSha')" >> $GITHUB_OUTPUT
            echo "COST=$(cat infracost.json | jq -r '.diffTotalMonthlyCost')" >> $GITHUB_OUTPUT

      - name: Append a line into a CSV
        uses: gr2m/write-csv-file-action@v1.x
        with:
          path: data/list.csv
          columns: date,sha,cost
          "date": ${{ steps.post-comment-step.outputs.INFRACOST_STEP_DATE }}
          "sha": ${{ steps.post-comment-step.outputs.INFRACOST_STEP_SHA }} 
          "cost": ${{ steps.post-comment-step.outputs.COST }}

  
      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{github.token}}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: CSV update
          file_pattern: 'data/*.csv'
          ref: ${{ github.head_ref }}