on: 
  pull_request:
    types: [closed]
env:
  # keys to connect to AWS
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
jobs:
  infracost:
    name: Infracost
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: Publish SNS Topic
      uses: nothingalike/sns-publish-topic@v1.6
      with:
        MESSAGE: "nuovo merge"
        TOPIC_ARN: "arn:aws:sns:eu-west-1:130746401085:github-action-dtm-sw-engineering.fifo"
